import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Link from "next/link";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lvan Ni | Designer & Developer",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <header className="flex justify-between items-center p-4">
          <Link href="/">L_N</Link>
          <Link href="/projects">_Projects</Link>
          <Link href="/about">_About</Link>
        </header>
        {children}
        <footer className="flex justify-between items-center p-4">
          <p>copyright©lvanni</p>
          <a href="https://www.linkedin.com/in/lvan-ni/">_LinkedIn</a>
          <a href="https://github.com/lvan-ni">_Github</a>
        </footer>
      </body>
    </html>
  );
}
